name: Build-Test

on:
  push:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-2022
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest CE release
      id: latest_release
      run: |
        $repo = "CombatExtended-Continued/CombatExtended" # 替换为您要下载的仓库名称
        $json = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/latest"
        $url = $json.assets | Where-Object { $_.name -like "*.zip" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $url -OutFile "release.zip"
    
    - name: Unzip release
      run: |
        Expand-Archive -Path "release.zip" -DestinationPath "./release/"
        mkdir libs
        cp release/CombatExtended/Assemblies/CombatExtended.dll ./libs
      
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Test Run
      run: |
            cd Source
            nuget restore RimArchive.csproj -SolutionDirectory ./RimArchive.sln
            msbuild RimArchive.sln -p:Configuration=release -p:ReferencePath=../libs
